name: Module CI/CD

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # create a zip file with all files required by the module to add to the release
      - name: Zip Files
        working-directory: ./
        run: zip -r ./module.zip ./module.json ./index.js ./templates/* ./lang/* ./module/* ./styles/* ./templates/*

      # Get the version from 'module.json'
      - name: Get Version
        shell: bash
        id: get-version
        run: |
          MODULE_VERSION=$(grep -oP '(?<="version": ")[^"]+' module.json | tr -d '\n')
          echo "moduleVersion=$MODULE_VERSION" >> $GITHUB_ENV

      # Create a release for this specific version
      - name: Create Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # set this to false if you want to prevent updating existing releases
          name: ${{ env.moduleVersion }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json,./module.zip'
          tag: v${{ env.moduleVersion }}
